/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.breathalyzer;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void testRunApp() {
        App classUnderTest = new App();
        classUnderTest.runApp();
    }
}
